### ISSUE TITLE
Pre-customized Grafana Dashboard Image

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-operator#110]
Currently, the Grafana dashboard image deployed by the Operator is a vanilla upstream Grafana image, which the Operator (or various scripts like rh-jmc-team/container-jfr's `smoketest.sh`) need to configure by performing various HTTP requests to create the default dashboard. This configuration is is not really configurable at deploy time, only at Operator build time, so there is no reason that the configurations should be done at deploy time. They can and should instead be performed at image creation time, by using a simple Dockerfile based on top of the upstream vanilla Grafana dashboard image and including the dashboard.json. The Operator can then deploy this Grafana container within the ContainerJFR pod instead, and no longer carry its own in-source copy of the dashboard definition JSON string (`pkg/controller/grafana/dashboard.go`), and not need to perform additional HTTP requests against the dashboard to check its health and configure the dashboard.

This same image-build-time configuration may also apply to the configuration for linking the jfr-datasource into the Grafana image, but maybe not.

This customized Grafana image should probably be split out into a new repo like `rh-jmc-team/grafana-dashboard`. This way it can be easily (re)built on its own and consumed by various deployments, including the Operator.

**Comment by andrewazores** [comment]
@vic-ma would this task interest you?

**Comment by vic-ma** [comment]
I'd prefer to work on cjfr/cjfr-core for now.
