### ISSUE TITLE
Connection to Grafana container fails

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-operator#112]
In diagnosing/testing the current broken Grafana setup when deploying with the Operator, I now have a setup where the ContainerJFR instance is properly able to recognize and attempt to connect to the Grafana container (see rh-jmc-team/containerjfr#278). But, when I click the "View in Grafana..." menu item of a recording, I am brought to a Grafana dashboard that has no jfr-datasource configured and no preset dashboard definition. This is seen in the Operator logs:

```
{"level":"error","ts":1601325018.8350742,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"grafana-controller","request":"default/containerjfr-grafana","error":"Get https://containerjfr-grafana-default.apps-crc.testing/api/health: x509: certificate signed by unknown authority","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/andrew/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/andrew/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/andrew/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/andrew/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/andrew/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/andrew/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/andrew/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```

It seems the Operator's grafana-controller fails to connect to the Grafana container due to a self-signed cert issue, which results in the Operator never configuring the Grafana container's jfr-datasource or dashboard.

**Comment by andrewazores** [comment]
@ebaron it seems like a temporary hack to get this working is just to set the env var `TLS_VERIFY=false`, I guess? Your exploration with cert-manager and other proper TLS cert management would lead to an actual solution to this problem down the line. For now in development and internal testing, setting it to `false` would work well enough.

I'll take a look and verify that assumption.

**Comment by andrewazores** [comment]
Setting `TLS_VERIFY=false` does seem to do the trick as a workaround. I did this directly in the clusterserviceversion, but it should also be doable by simply editing the operator deployment.

**Comment by ebaron** [comment]
Makes sense, TLS support is very much a work-in-progress at the moment anyway.

**Comment by andrewazores** [comment]
I'm going to mark this as a "wontfix" but leave it open for now, since it's sort of an indirect bug as a result of that larger TLS story.

**Comment by ebaron** [comment]
I think this can be closed now.
