### ISSUE TITLE
Work with Kubernetes

### ISSUE THREAD

**Issue by ebaron** [rh-jmc-team/container-jfr-operator#120]
We should detect whether the operator is running on OpenShift or Kubernetes and it should run properly in both scenarios. This will mainly mean using Ingress for Kubernetes and Route for OpenShift.

**Comment by ebaron** [comment]
In order to detect whether we're running on OpenShift, we can use the Manager's RESTMapper (`mgr.GetRESTMapper()`) to check if the server knows about the Route kind. This seems to work:
```go
func (r *ReconcileContainerJFR) isOpenShift() (bool, error) {
	// Look up RESTMapping for Route to check if the cluster is running OpenShift
	_, err := r.RESTMapper.RESTMapping(schema.GroupKind{
		Group: openshiftv1.GroupVersion.Group,
		Kind:  "Route",
	}, openshiftv1.GroupVersion.Version)
	if err != nil {
		// No matches for Route GVK
		if meta.IsNoMatchError(err) {
			return false, nil
		}
		// Unexpected error occurred
		return false, err
	}
	return true, nil
}
```

We may want to abstract this method to a type we can reuse among different controllers, assuming we need to check in more than one controller.

We should also verify this works using Minikube: https://minikube.sigs.k8s.io/docs/start/

**Comment by ebaron** [comment]
The `oc` commands in our Makefile and README should be replaced with `kubectl`, along with an environment variable to override the command if the user wishes.

**Comment by andrewazores** [comment]
Interestingly, the latest `operator-sdk` versions no longer have things like `operator-sdk build`. Instead, doing `operator-sdk init` to set up the project also scaffolds a `Makefile`, which has a *very* similar structure to ours, and already uses `kubectl`:

[Makefile.txt](https://github.com/rh-jmc-team/container-jfr-operator/files/5894635/Makefile.txt)

This looks like it also allows for building the operator binary without also loading it to an OCI registry, which would be useful/necessary for downstream builds of the Operator.

I'll check around if there is an easy upgrade path from `operator-sdk v0.15.2` to a `1.x` with this new setup.

**Comment by ebaron** [comment]
Here's the migration guide: https://sdk.operatorframework.io/docs/upgrading-sdk-version/

It looks like a big job, at least to cross the 1.0 boundary, but something we should do.

**Comment by ebaron** [comment]
@andrewazores I filed https://github.com/rh-jmc-team/container-jfr-operator/issues/148 for upgrading Operator SDK.
