### ISSUE TITLE
Upgrade to Operator SDK 1.3 (or newer)

### ISSUE THREAD

**Issue by ebaron** [rh-jmc-team/container-jfr-operator#148]
Currently, the newest Operator SDK is 1.3.0. We're currently using 0.15.2. It seems like a lot of breaking changes came with the 1.0 release. Nevertheless, we should upgrade to the newest version.

Here is an upgrade guide: https://sdk.operatorframework.io/docs/upgrading-sdk-version/
(Note: prior to 0.18.0 the guide is here: https://sdk.operatorframework.io/docs/upgrading-sdk-version/version-upgrade-guide/).

There is also a guide specific to Golang operators, which is also recommended reading: https://sdk.operatorframework.io/docs/building-operators/golang/migration/

**Comment by andrewazores** [comment]
I'm giving this a shot but I'm running into many stumbling blocks with weird (to me, anyway) package versioning in `go.mod` :-/ might take me a while to work through since I'm really not very familiar with Go's whole module/package ecosystem and tooling and these pseudoversions.

**Comment by ebaron** [comment]
Thanks! Let me know if I can help with any particular problems.

**Comment by andrewazores** [comment]
Fixed in #153.
