### ISSUE TITLE
Grafana dashboard container uses default admin auth credentials

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-operator#51]
The Grafana dashboard container comes pre-configured with a default admin account. This should be disabled and some sort of secret configuration added so that the outside world does not have admin access to the Grafana container. Relating to #50 , there should be some access token that the operator service account can use for configuring the Grafana instance, and this (or a similar) token, or some non-default credentials, should be somehow attached to the Grafana instance in a way that the cluster admin is still able to get admin access into the Grafana instance as well, in case there is a need for additional configuration.

**Comment by andrewazores** [comment]
https://grafana.com/docs/grafana/latest/installation/docker/

https://grafana.com/docs/grafana/latest/auth/overview/

https://grafana.com/docs/grafana/latest/auth/generic-oauth/

Grafana has what looks to be a pretty easy way to hook in to external OAuth. We should be able to set this up to work with OpenShift OAuth, possibly by also running OpenShift oauth-proxy in the container-jfr pod.

**Comment by andrewazores** [comment]
Ideally we don't add the oauth-proxy container, since this carries again some more overhead that can probably be avoided, and which we are really trying to avoid carrying for the minimal deployment case in particular. And we definitely want to avoid any scenario where we conditionally deploy the proxy for full setups and use direct auth (as in the current implementation) for minimal setups.

https://docs.openshift.com/container-platform/4.1/authentication/understanding-authentication.html

https://docs.openshift.com/container-platform/4.1/authentication/configuring-internal-oauth.html

**Comment by andrewazores** [comment]
https://community.grafana.com/t/openshift-generic-oauth/2148

https://blog.sakuragawa.moe/deploy-granafa-with-prometheus-and-oauth2-on-openshift/

**Comment by andrewazores** [comment]
Ran into a stumbling block:

https://github.com/openshift/origin/issues/18013

**Comment by andrewazores** [comment]
Possible workaround:

https://community.grafana.com/t/how-to-config-api-url-when-there-is-no-userinfo-endpoint-provided-by-my-oauth-server/719/4

**Comment by andrewazores** [comment]
The credentials for the default basic auth admin user can be configured by setting the environment variables `GF_SECURITY_ADMIN_USER` and `GF_SECURITY_ADMIN_PASSWORD`. If the operator sets these (or at least the password) in the Grafana container env vars then the credentials can at least be non-default and customized by the admin for each installed operator instance.

@ebaron does it make sense to add this kind of configuration to the ContainerJFR CRD? It could also be set as an environment variable on the operator itself (or its parent deployment). The former way makes sense in that this allows for separate ContainerJFR instances to have their own configurations, whereas the latter makes sense because the Grafana instance is more of a sibling to the ContainerJFR than a part of it.

**Comment by ebaron** [comment]
Would it make sense to have the operator generate these credentials? The operator could store the credentials in a Secret and populate these environment variables directly from the Secret, without exposing the credentials: https://docs.openshift.com/container-platform/4.3/nodes/pods/nodes-pods-secrets.html

**Comment by andrewazores** [comment]
Grafana now uses generated non-default Basic credentials behind TLS termination, so the need for OpenShift OAuth integration is no longer urgent or even particularly clear. Closing.
