### ISSUE TITLE
container-jfr log level env var should be controllable via CR spec

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-operator#63]
container-jfr uses an environment variable to set its logging level. There should be a way to set this variable via the operator's ContainerJFR CRs.

**Comment by Alexjsenn** [comment]
@andrewazores @ebaron 
I was working on this but remembered having seen a PR that changed the way the logging level was specified. Looking at rh-jmc-team/container-jfr#308 it seems that the env var is not used anymore. Does it make sense to allow `CONTAINER_JFR_JUL_CONFIG`  to be configurable via the ContainerJFR CRs? Given that it would also involve a configuration file (which I think would need to be in the pvc) it may not be ideal.

**Comment by andrewazores** [comment]
I think you're right, it's probably not worth adding this to CR(D) anymore since it's more complex now than it was when this issue was filed.
