### ISSUE TITLE
unsupported type invalid type for invalid type, from ./pkg/apis/rhjmc/v1alpha1.ContainerJFR

### ISSUE THREAD

**Issue by dsgrieve** [rh-jmc-team/container-jfr-operator#93]
Cannot build container-jfr-operator. I'm trying to build on windows subsystem for linux. I've had no issue building other pieces and parts of container-jfr

> container-jfr-operator$ make clean image BUILDER=$(which docker)
rm -rf build/_output
operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [rhjmc:[v1alpha1 v1alpha2], ]
F0730 17:13:10.063606   10829 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from ./pkg/apis/rhjmc/v1alpha1.ContainerJFR
make: *** [Makefile:22: k8s] Error 255

> git show HEAD
commit f6e3e25d18b3201df2e6232a44c532210eadb45f (HEAD -> main, origin/main, origin/HEAD)
Author: Elliott Baron <ebaron@redhat.com>
Date:   Tue Jul 21 10:44:10 2020 -0400

    Reorder undeploy target to better handle recordings (#92)

> go version
go version go1.13.3 linux/amd64

> uname -a
Linux ######## 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux

>  docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by ebaron** [comment]
Hi David, I believe one of our team members (@Alexjsenn) encountered this issue as well. If I recall correctly, it was an Operator SDK issue that requires the `GOROOT` environment variable to be set: https://github.com/operator-framework/operator-sdk/issues/2619#issuecomment-594061903

**Comment by dsgrieve** [comment]
`export GOROOT=$(go env GOROOT)` worked. Thanks.

**Comment by andrewazores** [comment]
@ebaron do we need to document `GOROOT` in the build instructions of the readme? Or is this a build environment-specific fix?

**Comment by ebaron** [comment]
> @ebaron do we need to document `GOROOT` in the build instructions of the readme? Or is this a build environment-specific fix?

I think it's worth documenting. I'll add something to the README.
