### ISSUE TITLE
WebSocket API calls should be replaced with HTTP REST calls

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-operator#96]
See:
- https://github.com/rh-jmc-team/container-jfr/pull/222
- https://github.com/rh-jmc-team/container-jfr/pull/225

JMX connections may be secured and require user authentication. For various reasons, this authentication layer will not be implemented across the WebSocket Command Channel, so any such API calls are being re-implemented with HTTP request handlers. The JMX auth credentials will then be supplied using an optional HTTP header. Connection failures will result in a `4xx` status code (currently `407`) from the ContainerJFR server to indicate to clients that the request was refused due to target connection authentication, as opposed to the `401` used to signify lacking client auth from ex. an OpenShift account token.

**Comment by ebaron** [comment]
This has been partially fixed with #108, but let's leave this open until we have the JMX authentication included as well.
