### ISSUE TITLE
Operator should be able to set ContainerJFR's RJMX credentials

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-operator#97]
See https://github.com/rh-jmc-team/container-jfr/issues/221

**Comment by ebaron** [comment]
For now, this should involve generating a password (using "containerjfr" for the username is probably fine), and passing the credentials to Container JFR in the deployment's pod template with the environment variables added in https://github.com/rh-jmc-team/container-jfr/pull/230.

For generating the password, perhaps we can make use of this existing function:
https://github.com/rh-jmc-team/container-jfr-operator/blob/2f6dce3ae7918c117c55bfd0fbbc821544591ff3/pkg/controller/containerjfr/resource_definitions/resource_definitions.go#L248-L256

**Comment by ebaron** [comment]
Fixed with #103
